#!/usr/bin/env bash

# Debugging in bash (based on http://mywiki.wooledge.org/BashGuide/Practices#Activate_Bash.27s_Debug_Mode)

__debug_set_x()
{
    if [[ $1 == - ]]
    then
        set -x
    elif [[ $1 == + ]]
    then
        set +x
        exec 4>&-
    elif [[ $1 && -d ${1%/*} ]]
    then
        exec 4>>"$1"
        BASH_XTRACEFD=4
        set -x
    fi
}
